spring: 
    data:
        mongodb:
            port: 27017
            host: localhost
            database: shop
    datasource:
        url: jdbc:mysql://localhost:3306/auth?serverTimezone=UTC&createDatabaseIfNotExist=true