spring:
  datasource:
    url: jdbc:postgresql://db-user:5432/auth
    driver-class-name: org.postgresql.Driver
    username: auth 
    password: 500290
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true  