spring:
  datasource:
    url: jdbc:postgresql://db-auth:5432/auth
    driver-class-name: org.postgresql.Driver
    username: auth 
    password: 500290
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  
  data:
    mongodb:
      port: 27017
      host: mongodb-auth
      database: tockens
      username: root
      password: 500290
      authentication-database: root
      uri: mongodb://root:500290@mongodb-auth:27017/tockens?authSource=root  