spring:
    mail: 
        host: smtp.gmail.com
        port: 587
        username: mihaila4038@gmail.com
        password: baib mghq usxc gjpq
        properties: 
            mail.smtp:
                auth: true
                starttls.enable: true
                
supportEmail:  mihaila4038@gmail.com
adminEmail:  mihaila4038@yandex.ru