spring:
  datasource:
    url: jdbc:mysql://localhost:3306/products?serverTimezone=UTC&createDatabaseIfNotExist=true

  # set up initial data
  sql.init.mode: always
  jpa.defer-datasource-initialization: true