spring:
  datasource:
    #url: jdbc:postgresql://db-product:5432/products
    url: jdbc:postgresql://localhost:5432/products
    #username: products
    username: postgres
    password: 500290    
  
  # set up initial data
  sql.init.mode: always
  jpa.defer-datasource-initialization: true