spring:
  datasource:
    #url: jdbc:postgresql://db-user:5432/users
    #username: users 
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: 500290    
  
  # set up initial data
  sql.init.mode: always
  jpa.defer-datasource-initialization: true